wallpaper {
    monitor = eDP-1
    path = ~/pictures/wallpaper/綠色女孩.jpeg
    fit_mode = cover
}
wallpaper {
    monitor = DP-1
    path = ~/pictures/wallpaper/六花.webp
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-1
    path = ~/pictures/wallpaper/六花.webp
    fit_mode = cover
}

splash = false
