preload = /home/creeper/picture/wallpaper/1690615522196.jpg
preload = /home/creeper/picture/wallpaper/1712718044669.png

wallpaper = eDP-1,/home/creeper/picture/wallpaper/1712718044669.png
wallpaper = HDMI-A-1,/home/creeper/picture/wallpaper/1712718044669.png

splash = false
