preload = /home/creeper/pictures/wallpaper/綠色女孩.jpeg
preload = /home/creeper/pictures/wallpaper/六花.webp

wallpaper = eDP-1,/home/creeper/pictures/wallpaper/綠色女孩.jpeg
wallpaper = DP-1,/home/creeper/pictures/wallpaper/六花.webp

splash = true