$monitor-main = eDP-1
$monitor-view = HDMI-A-1

monitor = $monitor-main, 3072x1920@120, 0x1080, 1.5, transform, 0
workspace = 1, monitor:$monitor-main
workspace = 2, monitor:$monitor-main
workspace = 3, monitor:$monitor-main
workspace = 4, monitor:$monitor-main
workspace = 5, monitor:$monitor-main

monitor = $monitor-view,1920x1080@74.97,0x0,1, transform, 0
workspace =  6, monitor:$monitor-view
workspace =  7, monitor:$monitor-view
workspace =  8, monitor:$monitor-view
workspace =  9, monitor:$monitor-view
workspace = 10, monitor:$monitor-view

