$BUILTIN  = eDP-1
$KTC200HZ = DP-1
$KTC165HZ = HDMI-A-1

monitor = $KTC165HZ, 1920x1080@200, 0x0, 1, transform, 0
workspace = 1, monitor:$KTC165HZ
workspace = 2, monitor:$KTC165HZ
workspace = 3, monitor:$KTC165HZ
workspace = 4, monitor:$KTC165HZ

monitor = $KTC200HZ, 1920x1080@120, 1920x0, 1
workspace = 5, monitor:$KTC200HZ
workspace = 6, monitor:$KTC200HZ
workspace = 7, monitor:$KTC200HZ
workspace = 8, monitor:$KTC200HZ
workspace = 9, monitor:$KTC200HZ

# monitor = $BUILTIN, disable
monitor = $BUILTIN,1920x1080@144,3840x0,1
workspace = 10, monitor:$BUILTIN
